import { useState } from 'react';
import { useRouter } from 'next/router';
import AuthLayout from '@/layouts/Auth.layout';
import { Button, Text } from '@chakra-ui/react';
import FormItem from '@/components/FormItem';
import Link from '@/components/Link';
import { Formik, Form } from 'formik';
import Head from 'next/head';

const SignUp: React.FC = () => {
  const router = useRouter();
  const [error, setError] = useState<string>('');

  const handleSubmit = async ({ email, name, password, confirm_password, phone, role }: { email: string; name: string; password: string; confirm_password: string, phone: string, role: string }) => {
    setError('');

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      setError('Email is not valid');
      return;
    }

    if (password.length < 8) {
      setError('Password must be at least 8 characters long');
      return;
    }

    if (password !== confirm_password) {
      setError('Passwords do not match');
      return;
    }

    try {
      const response = await fetch('http://localhost:4000/users', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ email, name, password, confirm_password, phone, role }),
      });

      if (response.ok) {
        router.push('/');
      } else {
        const data = await response.json();
        setError(data.message || 'Something went wrong');
      }
    } catch (error) {
      console.error('An unexpected error occurred:', error);
      setError('An unexpected error occurred');
    }
  };

  return (
    <>
      <Head>
        <title>Sign Up - OS SMARTFARM</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <AuthLayout
        title='Create account'
        subtitle='Sign up to get started'
      >
        <Formik
          initialValues={{ email: '', name: '', password: '', confirm_password: '', phone:'', role: '' }}
          onSubmit={handleSubmit}
        >
          <Form>
            <div className='flex flex-col gap-y-6'>
              <FormItem.Input name='email' placeholder='E-mail' type='email' />
              <FormItem.Input name='name' placeholder='Username' type='text' />
              <FormItem.Password name='password' />
              <FormItem.Password name='confirm_password' placeholder='Confirm Password' />
            </div>

            <Button
              w={'100%'}
              mt={'2.5rem'}
              type='submit'
              size='lg'
            >
              SIGN UP
            </Button>

            {error && (
              <Text
                textAlign={'center'}
                letterSpacing={'-0.39 px'}
                lineHeight={'19.07px'}
                fontSize={'14px'}
                color='status.error'
                fontWeight={400}
                mt={2}
              >
                {error}
              </Text>
            )}

            <div className='flex justify-center items-center mt-6'>
              <Text
                letterSpacing={'-0.39 px'}
                lineHeight={'19.07px'}
                fontSize={'14px'}
                color='#8392AB'
                fontWeight={600}
                mr={1}
              >
                Already have an account?
              </Text>

              <Link href='/'>Sign in</Link>
            </div>
          </Form>
        </Formik>
      </AuthLayout>
    </>
  );
};

export default SignUp;
